version: '3'

services:

  git-server:
    image: jkarlos/git-server-docker
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - /media/tori/541c6833-3172-4b9f-a747-4d48ec0483c3/repo/git_repo/keys:/git-server/keys
    - /media/tori/541c6833-3172-4b9f-a747-4d48ec0483c3/repo/git_repo/repos:/git-server/repos