version: '2'

services:

  git-server:
    image: jkarlos/git-server-docker
    #build: .
    restart: always
    container_name: git-server
    ports:
      - "2222:22"
    volumes:
    - /home/tori/workspace/docker/docker_files/keys:/git-server/keys
    - /home/tori/workspace/docker/docker_files/repos:/git-server/repos

